/**
 * Generated by hand from supabase/migrations/0001_attestations.sql.
 *
 * Keep this file in sync whenever the SQL schema changes — we don't run
 * `supabase gen types` to avoid pulling the CLI into CI just for one
 * table.  The shape is small enough to maintain manually.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface AttestationRow {
  [key: string]: unknown;
  id: string;
  user_id: string;
  title: string;
  customer_name: string;
  customer_address: string;
  approval_data: Json;
  common_data: Json;
  /**
   * Snapshot of every per-document form, keyed by
   * `DocumentDescriptor.key` (eg. "coding", "safety", "siz", …).  Values
   * are the raw form objects — the *same* shape the DOCX generators
   * consume.  Storing the unparsed shape keeps storage decoupled from
   * the per-document zod schema (which may evolve independently).
   */
  documents_data: Record<string, Json>;
  created_at: string;
  updated_at: string;
}

export interface AttestationInsert {
  [key: string]: unknown;
  id?: string;
  user_id: string;
  title?: string;
  customer_name?: string;
  customer_address?: string;
  approval_data?: Json;
  common_data?: Json;
  documents_data?: Record<string, Json>;
  created_at?: string;
  updated_at?: string;
}

export interface AttestationUpdate {
  [key: string]: unknown;
  title?: string;
  customer_name?: string;
  customer_address?: string;
  approval_data?: Json;
  common_data?: Json;
  documents_data?: Record<string, Json>;
  updated_at?: string;
}

/**
 * One per-document form snapshot — see supabase/migrations/0002.
 * A row per (attestation, DocumentDescriptor.key), so editing one document
 * no longer rewrites the whole `attestations.documents_data` blob.
 */
export interface AttestationDocumentRow {
  [key: string]: unknown;
  attestation_id: string;
  key: string;
  data: Json;
  updated_at: string;
}

export interface AttestationDocumentInsert {
  [key: string]: unknown;
  attestation_id: string;
  key: string;
  data: Json;
  updated_at?: string;
}

export interface AttestationDocumentUpdate {
  [key: string]: unknown;
  data?: Json;
  updated_at?: string;
}

export interface Database {
  public: {
    Tables: {
      attestations: {
        Row: AttestationRow;
        Insert: AttestationInsert;
        Update: AttestationUpdate;
        Relationships: [];
      };
      attestation_documents: {
        Row: AttestationDocumentRow;
        Insert: AttestationDocumentInsert;
        Update: AttestationDocumentUpdate;
        Relationships: [];
      };
    };
    // Empty placeholders that still satisfy `GenericSchema` (which
    // expects Record<string, GenericView/GenericFunction>).  Using `{}`
    // here would degrade Schema to `never` and break every from() call.
    Views: { [key: string]: never };
    Functions: { [key: string]: never };
  };
}
